<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAw3i2b8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAw3i2b8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAw3i2b8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAw3i2b8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAw3i2b8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Aw3i2b8',
    'container.build_id' => '45c58f03',
    'container.build_time' => 1564915340,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAw3i2b8');
